---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: Workflows/ArgoCD
  home: My Workflows/Workflows/ArgoCD
spec:
  - template: ArgoCD delete application
    description: Delete Application in ArgoCD.
    scheduledStartDate: 2023-04-27T15:00:00+02:00
    dueDate: 2023-04-27T16:00:00+02:00
    phases:
      - phase: Delete Application in ArgoCD
        tasks:
          - name: Get configuration details
            type: xlrelease.ScriptTask
            description: Getting configuration details of the target deployment server.
            script: |-
              from com.xebialabs.xlrelease.domain.environments import LiveDeployment
              
              liveDeployment = deploymentServerApi.getLiveDeployment("${liveDeploymentId}")
              applicationName = liveDeployment.getApplication().getTitle().split(":")[0]
              statusWebhookEventSource = configurationApi.getConfiguration(liveDeployment.eventSourceId)
              
              releaseVariables['statusWebhookEventSourceId'] = statusWebhookEventSource.id
              releaseVariables['applicationName'] = applicationName
              releaseVariables['argoCDApiServer'] = statusWebhookEventSource["sourceServer"].id
          - name: Application details
            type: xlrelease.UserInputTask
            description: |-
              Please enter the application you want to delete.
              The application will also be deleted from Argo server
            variables:
              - applicationName
              - argoCDApiServer
          - name: Delete Application in ArgoCD
            type: argocd.RemoveApplication
            description: "Deleting **${applicationName}**"
            variableMapping:
              server: "${argoCDApiServer}"
            capabilities:
              - remote
            applicationName: "${applicationName}"
          - name: Delete configuration
            type: xlrelease.ScriptTask
            description: Deletes configuration from Digital.ai Release
              the deleted application.
            script: |-
              statusWebhookEventSource = configurationApi.getConfiguration("${statusWebhookEventSourceId}")
              liveDeploymentConfigs = statusWebhookEventSource.getProperty("liveDeploymentConfigs")
              applicationToDelete = "${applicationName}"
              
              configToDelete = None
              for config in liveDeploymentConfigs:
                  if config.getProperty("application") == applicationToDelete:
                      configToDelete = config
                      break
              
              if configToDelete:
                  liveDeploymentConfigs.remove(configToDelete)
                  statusWebhookEventSource.setProperty("liveDeploymentConfigs", liveDeploymentConfigs)
                  configurationApi.updateConfiguration("${statusWebhookEventSourceId}", statusWebhookEventSource)
                  configurationApi.deleteConfiguration(configToDelete.id)
        color: "#3d6c9e"
    kind: WORKFLOW
    tags:
      - Remote ArgoCD
      - application
      - delete
      - internal
    categories:
      - Application onboarding
    variables:
      - type: xlrelease.StringVariable
        key: liveDeploymentId
        requiresValue: false
        showOnReleaseStart: false
      - type: xlrelease.StringVariable
        key: statusWebhookEventSourceId
        requiresValue: false
        showOnReleaseStart: false
      - type: xlrelease.StringVariable
        key: applicationName
        showOnReleaseStart: false
        label: Application Name
        description: Application name to delete from ArgoCD
      - type: xlrelease.ReferenceVariable
        key: argoCDApiServer
        showOnReleaseStart: false
        label: ArgoCD API server
        description: ArgoCD Api Server connection details
        referencedType: argocd.APIServer
    disableNotifications: true
    author: Digital.ai
    logo:
      type: xlrelease.TemplateLogo
      contentType: image/png
      file: !file "template-logo/c9e27d5b1d5ed9738d58781439732acacd6b482d/argocd.svg"
    defaultTargetFolder: My Workflows/Workflow Executions
